export default [
  { label: "Albania", value: "Albania", code: "AL" },
  { label: "Andorra", value: "Andorra", code: "AD" },
  { label: "Argentina", value: "Argentina", code: "AR" },
  { label: "Australia", value: "Australia", code: "AU" },
  { label: "Austria", value: "Austria", code: "AT" },
  { label: "Bangladesh", value: "Bangladesh", code: "BD" },
  { label: "Belgium", value: "Belgium", code: "BE" },
  { label: "Bhutan", value: "Bhutan", code: "BT" },
  { label: "Bolivia", value: "Bolivia", code: "BO" },
  { label: "Botswana", value: "Botswana", code: "BW" },
  { label: "Brazil", value: "Brazil", code: "BR" },
  { label: "Bulgaria", value: "Bulgaria", code: "BG" },
  { label: "Cambodia", value: "Cambodia", code: "KH" },
  { label: "Canada", value: "Canada", code: "CA" },
  { label: "Chile", value: "Chile", code: "CL" },
  { label: "Colombia", value: "Colombia", code: "CO" },
  { label: "Croatia", value: "Croatia", code: "HR" },
  { label: "Czechia", value: "Czechia", code: "CZ" },
  { label: "Denmark", value: "Denmark", code: "DK" },
  { label: "Dominican Republic", value: "Dominican Republic", code: "DO" },
  { label: "Ecuador", value: "Ecuador", code: "EC" },
  { label: "Estonia", value: "Estonia", code: "EE" },
  { label: "Eswatini", value: "Eswatini", code: "SZ" },
  { label: "Finland", value: "Finland", code: "FI" },
  { label: "France", value: "France", code: "FR" },
  { label: "Germany", value: "Germany", code: "DE" },
  { label: "Ghana", value: "Ghana", code: "GH" },
  { label: "Greece", value: "Greece", code: "GR" },
  { label: "Greenland", value: "Greenland", code: "GL" },
  { label: "Guatemala", value: "Guatemala", code: "GT" },
  { label: "Hungary", value: "Hungary", code: "HU" },
  { label: "Iceland", value: "Iceland", code: "IS" },
  { label: "Indonesia", value: "Indonesia", code: "ID" },
  { label: "Ireland", value: "Ireland", code: "IE" },
  { label: "Israel", value: "Israel", code: "IL" },
  { label: "Italy", value: "Italy", code: "IT" },
  { label: "Japan", value: "Japan", code: "JP" },
  { label: "Jordan", value: "Jordan", code: "JO" },
  { label: "Kenya", value: "Kenya", code: "KE" },
  { label: "Kyrgyzstan", value: "Kyrgyzstan", code: "KG" },
  { label: "Latvia", value: "Latvia", code: "LV" },
  { label: "Lesotho", value: "Lesotho", code: "LS" },
  { label: "Lithuania", value: "Lithuania", code: "LT" },
  { label: "Luxembourg", value: "Luxembourg", code: "LU" },
  { label: "Malaysia", value: "Malaysia", code: "MY" },
  { label: "Mexico", value: "Mexico", code: "MX" },
  { label: "Mongolia", value: "Mongolia", code: "MN" },
  { label: "Montenegro", value: "Montenegro", code: "ME" },
  { label: "Netherlands", value: "Netherlands", code: "NL" },
  { label: "New Zealand", value: "New Zealand", code: "NZ" },
  { label: "Nigeria", value: "Nigeria", code: "NG" },
  { label: "North Macedonia", value: "North Macedonia", code: "MK" },
  { label: "North Mariana Islands", value: "North Mariana Islands", code: "MP" },
  { label: "Norway", value: "Norway", code: "NO" },
  { label: "Panama", value: "Panama", code: "PA" },
  { label: "Peru", value: "Peru", code: "PE" },
  { label: "Philippines", value: "Philippines", code: "PH" },
  { label: "Poland", value: "Poland", code: "PL" },
  { label: "Portugal", value: "Portugal", code: "PT" },
  { label: "Romania", value: "Romania", code: "RO" },
  { label: "Russia", value: "Russia", code: "RU" },
  { label: "Senegal", value: "Senegal", code: "SN" },
  { label: "Serbia", value: "Serbia", code: "RS" },
  { label: "Singapore", value: "Singapore", code: "SG" },
  { label: "Slovakia", value: "Slovakia", code: "SK" },
  { label: "South Africa", value: "South Africa", code: "ZA" },
  { label: "South Korea", value: "South Korea", code: "KR" },
  { label: "Spain", value: "Spain", code: "ES" },
  { label: "Sri Lanka", value: "Sri Lanka", code: "LK" },
  { label: "Sweden", value: "Sweden", code: "SE" },
  { label: "Switzerland", value: "Switzerland", code: "CH" },
  { label: "Taiwan", value: "Taiwan", code: "TW" },
  { label: "Thailand", value: "Thailand", code: "TH" },
  { label: "Turkey", value: "Turkey", code: "TR" },
  { label: "Uganda", value: "Uganda", code: "UG" },
  { label: "Ukraine", value: "Ukraine", code: "UA" },
  { label: "United Arab Emirates (UAE)", value: "United Arab Emirates", code: "AE" },
  { label: "United Kingdom (UK)", value: "United Kingdom", code: "GB" },
  { label: "United States of America (USA)", value: "United States", code: "US" },
  { label: "Uruguay", value: "Uruguay", code: "UY" },
  { label: "Egypt", value: "Egypt", code: "EG" },
  { label: "Pakistan", value: "Pakistan", code: "PK" },
  { label: "China", value: "China", code: "CN" },
  { label: "India", value: "India", code: "IN" },
  { label: "Laos", value: "Laos", code: "LA" },
  { label: "Nepal", value: "Nepal", code: "NP" },
  { label: "Rwanda", value: "Rwanda", code: "RW" },
  { label: "Vietnam", value: "Vietnam", code: "VN" },
  { label: "Bermuda", value: "Bermuda", code: "BM" },
  { label: "Puerto Rico", value: "Puerto Rico", code: "PR" },
  { label: "Réunion", value: "Réunion", code: "RE" },
  { label: "Faroe Islands", value: "Faroe Islands", code: "FO" },
  { label: "Hong Kong", value: "Hong Kong", code: "HK" },
  { label: "Isle of Man", value: "Isle of Man", code: "IM" },
];

export const getCountryCode = (country) => {
  if (CountryCodeObj[country]) return CountryCodeObj[country];
  else return "";
};

export const CountryCodeObj = {
  Albania: "AL",
  Andorra: "AD",
  Argentina: "AR",
  Australia: "AU",
  Austria: "AT",
  Bangladesh: "BD",
  Belgium: "BE",
  Bhutan: "BT",
  Bolivia: "BO",
  Botswana: "BW",
  Brazil: "BR",
  Bulgaria: "BG",
  Cambodia: "KH",
  Canada: "CA",
  Chile: "CL",
  Colombia: "CO",
  Croatia: "HR",
  Czechia: "CZ",
  Denmark: "DK",
  "Dominican Republic": "DO",
  Ecuador: "EC",
  Estonia: "EE",
  Eswatini: "SZ",
  Finland: "FI",
  France: "FR",
  Germany: "DE",
  Ghana: "GH",
  Greece: "GR",
  Greenland: "GL",
  Guatemala: "GT",
  Hungary: "HU",
  Iceland: "IS",
  Indonesia: "ID",
  Ireland: "IE",
  Israel: "IL",
  Italy: "IT",
  Japan: "JP",
  Jordan: "JO",
  Kenya: "KE",
  Kyrgyzstan: "KG",
  Latvia: "LV",
  Lesotho: "LS",
  Lithuania: "LT",
  Luxembourg: "LU",
  Malaysia: "MY",
  Mexico: "MX",
  Mongolia: "MN",
  Montenegro: "ME",
  Netherlands: "NL",
  "New Zealand": "NZ",
  Nigeria: "NG",
  "North Macedonia": "MK",
  "North Mariana Islands": "MP",
  Norway: "NO",
  Panama: "PA",
  Peru: "PE",
  Philippines: "PH",
  Poland: "PL",
  Portugal: "PT",
  Romania: "RO",
  Russia: "RU",
  Senegal: "SN",
  Serbia: "RS",
  Singapore: "SG",
  Slovakia: "SK",
  "South Africa": "ZA",
  "South Korea": "KR",
  Spain: "ES",
  "Sri Lanka": "LK",
  Sweden: "SE",
  Switzerland: "CH",
  Taiwan: "TW",
  Thailand: "TH",
  Turkey: "TR",
  Uganda: "UG",
  Ukraine: "UA",
  "United Arab Emirates": "AE",
  "United Kingdom": "GB",
  "United States": "US",
  Uruguay: "UY",
  Egypt: "EG",
  Pakistan: "PK",
  China: "CN",
  India: "IN",
  Laos: "LA",
  Nepal: "NP",
  Rwanda: "RW",
  Vietnam: "VN",
  Bermuda: "BM",
  "Puerto Rico": "PR",
  Réunion: "RE",
  "Faroe Islands": "FO",
  "Hong Kong": "HK",
  "Isle of Man": "IM",
};
