export default [
  { label: 'Bollards', value: 'Bollards' },
  { label: 'Architecture', value: 'Architecture' },
  { label: 'Vehicles (Non-Google)', value: 'Vehicles (Non-Google)' },
  { label: 'Google Cars', value: 'Google Cars' },
  { label: 'Utility Poles', value: 'Utility Poles' },
  { label: 'Flags', value: 'Flags' },
  { label: 'Street Signs', value: 'Street Signs' },
  { label: 'License Plates', value: 'License Plates' },
  { label: 'Trees', value: 'Trees' },
  { label: 'Mountains', value: 'Mountains' },
  { label: 'Language', value: 'Language' },
  { label: 'Internet Domain', value: 'Internet Domain' },
  { label: 'Vending Machines', value: 'Vending Machines' },
];
