export default [
  { country: 'United States', label: 'Alabama', value: 'Alabama' },
  { country: 'United States', label: 'Alaska', value: 'Alaska' },
  { country: 'United States', label: 'Arizona', value: 'Arizona' },
  { country: 'United States', label: 'Arkansas', value: 'Arkansas' },
  { country: 'United States', label: 'California', value: 'California' },
  { country: 'United States', label: 'Colorado', value: 'Colorado' },
  { country: 'United States', label: 'Connecticut', value: 'Connecticut' },
  { country: 'United States', label: 'Delaware', value: 'Delaware' },
  { country: 'United States', label: 'District of Columbia', value: 'District of Columbia' },
  { country: 'United States', label: 'Florida', value: 'Florida' },
  { country: 'United States', label: 'Georgia', value: 'Georgia' },
  { country: 'United States', label: 'Hawaii', value: 'Hawaii' },
  { country: 'United States', label: 'Idaho', value: 'Idaho' },
  { country: 'United States', label: 'Illinois', value: 'Illinois' },
  { country: 'United States', label: 'Indiana', value: 'Indiana' },
  { country: 'United States', label: 'Iowa', value: 'Iowa' },
  { country: 'United States', label: 'Kansas', value: 'Kansas' },
  { country: 'United States', label: 'Kentucky', value: 'Kentucky' },
  { country: 'United States', label: 'Louisiana', value: 'Louisiana' },
  { country: 'United States', label: 'Maine', value: 'Maine' },
  { country: 'United States', label: 'Maryland', value: 'Maryland' },
  { country: 'United States', label: 'Massachusetts', value: 'Massachusetts' },
  { country: 'United States', label: 'Michigan', value: 'Michigan' },
  { country: 'United States', label: 'Minnesota', value: 'Minnesota' },
  { country: 'United States', label: 'Mississippi', value: 'Mississippi' },
  { country: 'United States', label: 'Missouri', value: 'Missouri' },
  { country: 'United States', label: 'Montana', value: 'Montana' },
  { country: 'United States', label: 'Nebraska', value: 'Nebraska' },
  { country: 'United States', label: 'Nevada', value: 'Nevada' },
  { country: 'United States', label: 'New Hampshire', value: 'New Hampshire' },
  { country: 'United States', label: 'New Jersey', value: 'New Jersey' },
  { country: 'United States', label: 'New Mexico', value: 'New Mexico' },
  { country: 'United States', label: 'New York', value: 'New York' },
  { country: 'United States', label: 'North Carolina', value: 'North Carolina' },
  { country: 'United States', label: 'North Dakota', value: 'North Dakota' },
  { country: 'United States', label: 'Ohio', value: 'Ohio' },
  { country: 'United States', label: 'Oklahoma', value: 'Oklahoma' },
  { country: 'United States', label: 'Oregon', value: 'Oregon' },
  { country: 'United States', label: 'Pennsylvania', value: 'Pennsylvania' },
  { country: 'United States', label: 'Rhode Island', value: 'Rhode Island' },
  { country: 'United States', label: 'South Carolina', value: 'South Carolina' },
  { country: 'United States', label: 'South Dakota', value: 'South Dakota' },
  { country: 'United States', label: 'Tennessee', value: 'Tennessee' },
  { country: 'United States', label: 'Texas', value: 'Texas' },
  { country: 'United States', label: 'Utah', value: 'Utah' },
  { country: 'United States', label: 'Vermont', value: 'Vermont' },
  { country: 'United States', label: 'Virginia', value: 'Virginia' },
  { country: 'United States', label: 'Washington', value: 'Washington' },
  { country: 'United States', label: 'West Virginia', value: 'West Virginia' },
  { country: 'United States', label: 'Wisconsin', value: 'Wisconsin' },
  { country: 'United States', label: 'Wyoming', value: 'Wyoming' },
  { country: 'United States', label: 'American Samoa', value: 'American Samoa' },
  { country: 'United States', label: 'Guam', value: 'Guam' },
  { country: 'United States', label: 'Northern Mariana Islands', value: 'Northern Mariana Islands' },
  { country: 'United States', label: 'Puerto Rico', value: 'Puerto Rico' },
  { country: 'United States', label: 'Virgin Islands', value: 'Virgin Islands' },
  { country: 'Canada', label: 'Newfoundland and Labrador', value: 'Newfoundland and Labrador' },
  { country: 'Canada', label: 'Nova Scotia', value: 'Nova Scotia' },
  { country: 'Canada', label: 'Prince Edward Island', value: 'Prince Edward Island' },
  { country: 'Canada', label: 'New Brunswick', value: 'New Brunswick' },
  { country: 'Canada', label: 'Quebec', value: 'Quebec' },
  { country: 'Canada', label: 'Ontario', value: 'Ontario' },
  { country: 'Canada', label: 'Manitoba', value: 'Manitoba' },
  { country: 'Canada', label: 'Saskatchewan', value: 'Saskatchewan' },
  { country: 'Canada', label: 'Alberta', value: 'Alberta' },
  { country: 'Canada', label: 'British Columbia', value: 'British Columbia' },
  { country: 'Canada', label: 'Yukon', value: 'Yukon' },
  { country: 'Canada', label: 'Northwest Territories', value: 'Northwest Territories' },
  { country: 'Canada', label: 'Nunavut', value: 'Nunavut' },
  { country: 'Australia', label: 'New South Wales', value: 'New South Wales' },
  { country: 'Australia', label: 'Victoria', value: 'Victoria' },
  { country: 'Australia', label: 'Queensland', value: 'Queensland' },
  { country: 'Australia', label: 'Western Australia', value: 'Western Australia' },
  { country: 'Australia', label: 'South Australia', value: 'South Australia' },
  { country: 'Australia', label: 'Tasmania', value: 'Tasmania' },
  { country: 'Australia', label: 'Northern Territory', value: 'Northern Territory' }
]
