export default [
  { country: 'United States', region: 'Alabama' },
  { country: 'United States', region: 'Alaska' },
  { country: 'United States', region: 'Arizona' },
  { country: 'United States', region: 'Arkansas' },
  { country: 'United States', region: 'California' },
  { country: 'United States', region: 'Colorado' },
  { country: 'United States', region: 'Connecticut' },
  { country: 'United States', region: 'Delaware' },
  { country: 'United States', region: 'District of Columbia' },
  { country: 'United States', region: 'Florida' },
  { country: 'United States', region: 'Georgia' },
  { country: 'United States', region: 'Hawaii' },
  { country: 'United States', region: 'Idaho' },
  { country: 'United States', region: 'Illinois' },
  { country: 'United States', region: 'Indiana' },
  { country: 'United States', region: 'Iowa' },
  { country: 'United States', region: 'Kansas' },
  { country: 'United States', region: 'Kentucky' },
  { country: 'United States', region: 'Louisiana' },
  { country: 'United States', region: 'Maine' },
  { country: 'United States', region: 'Maryland' },
  { country: 'United States', region: 'Massachusetts' },
  { country: 'United States', region: 'Michigan' },
  { country: 'United States', region: 'Minnesota' },
  { country: 'United States', region: 'Mississippi' },
  { country: 'United States', region: 'Missouri' },
  { country: 'United States', region: 'Montana' },
  { country: 'United States', region: 'Nebraska' },
  { country: 'United States', region: 'Nevada' },
  { country: 'United States', region: 'New Hampshire' },
  { country: 'United States', region: 'New Jersey' },
  { country: 'United States', region: 'New Mexico' },
  { country: 'United States', region: 'New York' },
  { country: 'United States', region: 'North Carolina' },
  { country: 'United States', region: 'North Dakota' },
  { country: 'United States', region: 'Ohio' },
  { country: 'United States', region: 'Oklahoma' },
  { country: 'United States', region: 'Oregon' },
  { country: 'United States', region: 'Pennsylvania' },
  { country: 'United States', region: 'Rhode Island' },
  { country: 'United States', region: 'South Carolina' },
  { country: 'United States', region: 'South Dakota' },
  { country: 'United States', region: 'Tennessee' },
  { country: 'United States', region: 'Texas' },
  { country: 'United States', region: 'Utah' },
  { country: 'United States', region: 'Vermont' },
  { country: 'United States', region: 'Virginia' },
  { country: 'United States', region: 'Washington' },
  { country: 'United States', region: 'West Virginia' },
  { country: 'United States', region: 'Wisconsin' },
  { country: 'United States', region: 'Wyoming' },
  { country: 'United States', region: 'American Samoa' },
  { country: 'United States', region: 'Guam' },
  { country: 'United States', region: 'Northern Mariana Islands' },
  { country: 'United States', region: 'Puerto Rico' },
  { country: 'United States', region: 'Virgin Islands' },
  { country: 'Canada', region: 'Newfoundland and Labrador' },
  { country: 'Canada', region: 'Nova Scotia' },
  { country: 'Canada', region: 'Prince Edward Island' },
  { country: 'Canada', region: 'New Brunswick' },
  { country: 'Canada', region: 'Quebec' },
  { country: 'Canada', region: 'Ontario' },
  { country: 'Canada', region: 'Manitoba' },
  { country: 'Canada', region: 'Saskatchewan' },
  { country: 'Canada', region: 'Alberta' },
  { country: 'Canada', region: 'British Columbia' },
  { country: 'Canada', region: 'Yukon' },
  { country: 'Canada', region: 'Northwest Territories' },
  { country: 'Canada', region: 'Nunavut' },
  { country: 'Australia', region: 'New South Wales' },
  { country: 'Australia', region: 'Victoria' },
  { country: 'Australia', region: 'Queensland' },
  { country: 'Australia', region: 'Western Australia' },
  { country: 'Australia', region: 'South Australia' },
  { country: 'Australia', region: 'Tasmania' },
  { country: 'Australia', region: 'Northern Territory' },
];
